### ISSUE TITLE
Chevron right still has prop fill so color is not applying

### ISSUE THREAD

**Issue by teovillanueva** [Eronred/radix-ui-react-native-icons#1]
As the title says it looks like the "chevron-right" icon still has the `fill` prop on the `<Path />`.

I'll create a PR whenever I can! Great job with the lib, I've been really enjoying it :)

**Comment by Eronred** [comment]
Thank you for it @teovillanueva! Happy to hear it.
I have double-checked numerous times for these cases, but unfortunately, missed one 😄 Always welcome to any PR ✋🏻

**Comment by Eronred** [comment]
Just fixed it up, so closing the issue. Thanks for pointing it out!

**Comment by Eronred** [comment]
Thank you for it @teovillanueva! Happy to hear it. Just fixed it up, so closing the issue. Thanks for pointing it out!
